name: ECC

on:
  push:
    branches: [ travis_to_GitHubActions]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          DAPS_PASSWORD_DOCKER: ${{secrets.KEYSTORE_PASSWORD}}
          SSL_KEY_PASSWORD: ${{secrets.SSL_KEY_PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - name: Run Install
        run: ./ci/install.sh
        
      - name: Docker images
        run:  docker images
        
      - name: Run docker container HTTPS-HTTPS-mixed
        run: docker-compose -f ./ci/docker/test-cases/https-https-mixed/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test HTTPS-HTTPS-mixed
        run: newman run ./ci/docker/test-cases/https-https-mixed/HTTPS-HTTPS-mixed.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container HTTPS-HTTPS-mixed
        run: docker-compose -f ./ci/docker/test-cases/https-https-mixed/docker-compose.yml down -v
        
      - name: Run docker container HTTPS-HTTPS-form
        run: docker-compose -f ./ci/docker/test-cases/https-https-form/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test HTTPS-HTTPS-form
        run: newman run ./ci/docker/test-cases/https-https-form/HTTPS-HTTPS-form.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container HTTPS-HTTPS-form
        run: docker-compose -f ./ci/docker/test-cases/https-https-form/docker-compose.yml down -v
        
      - name: Run docker container HTTPS-HTTPS-header
        run: docker-compose -f ./ci/docker/test-cases/https-https-header/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test HTTPS-HTTPS-header
        run: newman run ./ci/docker/test-cases/https-https-header/HTTPS-HTTPS-header.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container HTTPS-HTTPS-header
        run: docker-compose -f ./ci/docker/test-cases/https-https-header/docker-compose.yml down -v
        
      - name: Run docker container HTTPS-IDSCP2-mixed
        run: docker-compose -f ./ci/docker/test-cases/https-idscp2-mixed/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/test-cases/https-idscp2-mixed/HTTPS-IDSCP2-mixed.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/test-cases/https-idscp2-mixed/docker-compose.yml down -v
        
      - name: Run docker container HTTPS-IDSCP2-form
        run: docker-compose -f ./ci/docker/test-cases/https-idscp2-form/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/test-cases/https-idscp2-form/HTTPS-IDSCP2-form.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/test-cases/https-idscp2-form/docker-compose.yml down -v
        
      - name: Run docker container HTTPS-IDSCP2-header
        run: docker-compose -f ./ci/docker/test-cases/https-idscp2-header/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/test-cases/https-idscp2-header/HTTPS-IDSCP2-header.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/test-cases/https-idscp2-header/docker-compose.yml down -v
        
      - name: Run docker container WS-WS
        run: docker-compose -f ./ci/docker/test-cases/ws-ws/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/test-cases/ws-ws/WS-WS.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/test-cases/ws-ws/docker-compose.yml down -v
        
      - name: Run docker container WS-IDSCP2
        run: docker-compose -f ./ci/docker/test-cases/ws-idscp2/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/test-cases/ws-idscp2/WS-IDSCP2.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/test-cases/ws-idscp2/docker-compose.yml down -v

      
