name: ECC

on:
  push:
    branches: [ travis_to_GitHubActions]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - name: Run Install
        run: ./ci/install.sh
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
              
      - name: Run docker container
        run: sudo docker-compose -f ./ci/docker/docker-compose.yml up 
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          DAPS: false
          CH: false
          DAPS_KEYSTORE_PASSWORD_DOCKER: ${{secrets.KEYSTORE_PASSWORD}}
          SSL_KEY_PASSWORD: ${{secrets.SSL_KEY_PASSWORD}}
        
      - name: Wait for cointainer starting
        run: sleep 60 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: ./ci/test.sh
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/docker-compose.yml down

      
