name: ECC

on:
  push:
    branches: [ travis_to_GitHubActions]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          DAPS_PASSWORD_DOCKER: ${{secrets.KEYSTORE_PASSWORD}}
          SSL_KEY_PASSWORD: ${{secrets.SSL_KEY_PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - name: Run Install
        run: ./ci/install.sh
        
      - name: Docker images
        run:  docker images
        
      - name: Run docker container HTTPS-HTTPS
        run: docker-compose -f ./ci/docker/https-https/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/https-https/HTTPS-HTTPS.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container HTTPS-HTTPS
        run: docker-compose -f ./ci/docker/https-https/docker-compose.yml down
        
      - name: Run docker container HTTPS-IDSCP
        run: docker-compose -f ./ci/docker/https-idscp2/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 120 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run Test
        run: newman run ./ci/docker/https-idscp2/HTTPS-IDSCP2.json --timeout-request 120000 --insecure --bail --verbose
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/https-idscp2/docker-compose.yml down

      
