name: ECC

on:
  push:
    branches: [ travis_to_GitHubActions]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          DAPS_PASSWORD_DOCKER: ${{secrets.KEYSTORE_PASSWORD}}
          SSL_KEY_PASSWORD: ${{secrets.SSL_KEY_PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - name: Run Install
        run: ./ci/install.sh
        
      - name: Docker images
        run:  docker images
        
      - name: Run docker container
        run: docker-compose -f ./ci/docker/docker-compose.yml up -d
        
      - name: Wait for cointainer starting
        run: sleep 60 
        
      - name: Check if the container is up and running
        run: docker ps -a 
      
      - name: Run curl
        run: |
                curl --location --request POST 'https://localhost:8084/proxy' \
                    --header 'Content-Type: text/plain' \
                    --data-raw '{
                        "multipart": "mixed",
                        "Forward-To": "https://localhost:8889/data",
                         "message": {
                          "@context" : {
                            "ids" : "https://w3id.org/idsa/core/"
                          },
                          "@type" : "ids:ArtifactRequestMessage",
                          "@id" : "https://w3id.org/idsa/autogen/artifactRequestMessage/76481a41-8117-4c79-bdf4-9903ef8f825a",
                          "ids:issued" : {
                            "@value" : "2020-11-25T16:43:27.051+01:00",
                            "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
                          },
                          "ids:modelVersion" : "4.0.0",
                          "ids:issuerConnector" : {
                            "@id" : "http://w3id.org/engrd/connector/"
                          },
                          "ids:requestedArtifact" : {
                           "@id" : "http://w3id.org/engrd/connector/artifact/1"
                          }
                        },
                        "payload" : {
                            "catalog.offers.0.resourceEndpoints.path":"/pet2"
                            }
                }'|
        
      - name: Stop docker container
        run: docker-compose -f ./ci/docker/docker-compose.yml down      
